Class {
	#name : 'RuntimeTypeCollectorTypePrintingVisitor',
	#superclass : 'Object',
	#category : 'Runtime Type Collector-Visitors',
	#package : 'Runtime Type Collector',
	#tag : 'Visitors'
}

{ #category : 'accessing' }
RuntimeTypeCollectorTypePrintingVisitor >> visitAssociationType: aType [ 

	
]

{ #category : 'accessing' }
RuntimeTypeCollectorTypePrintingVisitor >> visitBlockType: aType [ 


]

{ #category : 'accessing' }
RuntimeTypeCollectorTypePrintingVisitor >> visitCollectionType: aType [ 

	
]

{ #category : 'accessing' }
RuntimeTypeCollectorTypePrintingVisitor >> visitDictionaryType: aType [ 

	
]

{ #category : 'accessing' }
RuntimeTypeCollectorTypePrintingVisitor >> visitSimpleType: aType [ 


]

{ #category : 'accessing' }
RuntimeTypeCollectorTypePrintingVisitor >> visitType: aType [ 


]

{ #category : 'accessing' }
RuntimeTypeCollectorTypePrintingVisitor >> visitTypeSet: aTypeSet [

	
]
